### PR TITLE
show all tag names in subtitle

### PR DESCRIPTION
**Pull request by winking324**
image

### CODE REVIEW

**Comment by FireFingers21** [comment]
My original decision to only display the first tag name was to prevent the URL from being obstructed for bookmarks with a lot of tags. I can work with this, but what's your use case for wanting all the tags in the subtitle?

**Comment by winking324** [comment]
Oh, I see. My purpose is to give better tips and find what is needed. Showing only one tag in the process of looking for bookmarks confuses me if these are what I need. For example, only the [Bookmark] tag is displayed, but I'm looking for the [Tool] tag.
Emmmm, it would be better to only display the tags that match the query?

**Comment by winking324** [comment]
So I added a configuration option to control this behavior, do you think that's okay?

**Comment by FireFingers21** [comment]
That's definitely okay, thanks for your submission! I've implemented it with a few formatting tweaks. That, on top of some other unrelated changes, means I unfortunately can't simply merge the PR without causing a conflict. Your feature has been added though, and I aim to have the workflow updated soon.

**Pull request closed without merging**
